# This is the base config for Jekyll Minima theme.
minima:
  skin: dark
  date_format: "%Y/%m/%d"
remote_theme: jekyll/minima

# CC-BY-SA 4.0 license
license:
  enable: true
  license: "CC BY-SA 4.0"
  license_url: "http://creativecommons.org/licenses/by-sa/4.0/"

# Language setting
lang: "zh-tw"
author: "SyuanTsai"