# This is the base config for Jekyll Minima theme.
minima:
  skin: dark
  date_format: "%Y/%m/%d"
  social_links:
    - { platform: github,  user_url: "https://github.com/SyuanTsai" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/tw-syuan" }
remote_theme: jekyll/minima


# Default Attributes
## Docs: https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  - { { site.data.config.creativeCommonsLicenses.yml } }
  #2- { { site.data.config.social_links.yml } }


# Page Language setting
lang: "zh-tw"
author: "SyuanTsai"





# Debug Settings
# Page Parameter Debugging Dedicated
# name rules => directoryPath/directoryPath/fileName: true/false
debug_tags:
  _layouts-layout: false

# Page Parameter Comments Dedicated
show_comments:
    _layout: false