# This is the base config for Jekyll Minima theme.
minima:
  skin: dark
  date_format: "%Y/%m/%d"
remote_theme: jekyll/minima


# Default Attributes
## Docs: https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  - { { site.data.config.creativeCommonsLicenses.yml } }

# Page Language setting
lang: "zh-tw"
author: "SyuanTsai"