# This is the base config for Jekyll Minima theme.
minima:
  skin: dark
  date_format: "%Y/%m/%d"
remote_theme: jekyll/minima

# CC-BY-SA 4.0 license
license:
   enable: true
#   license: "CC BY-SA 4.0"
#   license_url: "http://creativecommons.org/licenses/by-sa/4.0/"
#   author: SyuanTsai
#   link: 本文連結
#   license_title: 版權聲明
#   license_content: '除非另有標注，部落格中所有文章，均採用
#      <a href="%s" rel="external nofollow" target="_blank">%s</a> 許可協議。
#      轉載請標明作者、連結與出處！'

# Language setting
lang: "zh-TW"