#!/usr/bin/env python3
"""Generate category, tag, and monthly archive entry pages from canonical data."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from validate_posts import discover_markdown, parse_front_matter


GENERATED_MARKER = "<!-- Generated by scripts/generate_discovery_pages.py; do not edit directly. -->"
GENERATED_DIRECTORIES = ("categories", "tags", "archives")


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def front_matter(fields: list[tuple[str, str]]) -> str:
    lines = ["---"]
    lines.extend(f"{name}: {value}" for name, value in fields)
    lines.extend(("---", GENERATED_MARKER, ""))
    return "\n".join(lines)


def load_taxonomy(root: Path) -> dict[str, list[dict[str, str]]]:
    path = root / "_data/taxonomy.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    return {
        "categories": list(data["categories"]),
        "tags": list(data["tags"]),
    }


def expected_pages(root: Path) -> dict[Path, str]:
    taxonomy = load_taxonomy(root)
    pages: dict[Path, str] = {}

    for category in taxonomy["categories"]:
        slug = category["slug"]
        pages[Path("categories") / f"{slug}.markdown"] = front_matter(
            [
                ("layout", "taxonomy"),
                ("title", quoted(category["name"])),
                ("description", quoted(category["description"])),
                ("eyebrow", quoted("Category")),
                ("taxonomy_type", "category"),
                ("taxonomy_slug", slug),
                ("permalink", f"/categories/{slug}/"),
            ]
        )

    for tag in taxonomy["tags"]:
        slug = tag["slug"]
        description = tag.get("description", f"所有標記為「{tag['name']}」的文章。")
        pages[Path("tags") / f"{slug}.markdown"] = front_matter(
            [
                ("layout", "taxonomy"),
                ("title", quoted(tag["name"])),
                ("description", quoted(description)),
                ("eyebrow", quoted("Tag")),
                ("taxonomy_type", "tag"),
                ("taxonomy_slug", slug),
                ("permalink", f"/tags/{slug}/"),
            ]
        )

    archive_keys: set[tuple[str, str]] = set()
    for post_path in discover_markdown(root / "_posts"):
        published = str(parse_front_matter(post_path).fields["date"])
        archive_keys.add((published[:4], published[5:7]))

    for year, month in sorted(archive_keys):
        pages[Path("archives") / year / f"{month}.markdown"] = front_matter(
            [
                ("layout", "archive"),
                ("title", quoted(f"{year} 年 {month} 月")),
                ("description", quoted(f"{year} 年 {month} 月發布的文章。")),
                ("eyebrow", quoted("Archive")),
                ("archive_year", quoted(year)),
                ("archive_month", quoted(month)),
                ("permalink", f"/archives/{year}/{month}/"),
            ]
        )

    return pages


def generated_files(root: Path) -> set[Path]:
    paths: set[Path] = set()
    for directory_name in GENERATED_DIRECTORIES:
        directory = root / directory_name
        if not directory.is_dir():
            continue
        for path in directory.rglob("*.markdown"):
            if GENERATED_MARKER in path.read_text(encoding="utf-8"):
                paths.add(path.relative_to(root))
    return paths


def check(root: Path, expected: dict[Path, str]) -> list[str]:
    errors: list[str] = []
    for relative_path, content in expected.items():
        path = root / relative_path
        if not path.is_file():
            errors.append(f"缺少產生頁面 `{relative_path}`")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"產生頁面 `{relative_path}` 未同步")

    for relative_path in sorted(generated_files(root) - expected.keys()):
        errors.append(f"存在已失效的產生頁面 `{relative_path}`")
    return errors


def write(root: Path, expected: dict[Path, str]) -> None:
    for relative_path in generated_files(root) - expected.keys():
        (root / relative_path).unlink()

    for relative_path, content in expected.items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="Only verify generated pages are current")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    try:
        expected = expected_pages(root)
    except (KeyError, TypeError, ValueError, json.JSONDecodeError, OSError) as error:
        print(f"Discovery page generation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        errors = check(root, expected)
        if errors:
            print("Discovery pages are not current:", file=sys.stderr)
            for error in errors:
                print(f"- {error}", file=sys.stderr)
            return 1
        print(f"Verified {len(expected)} generated discovery pages.")
        return 0

    write(root, expected)
    print(f"Generated {len(expected)} discovery pages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
